import type { City } from "./types"

// Sample data for the destinations page
export const cities: City[] = [
  {
    id: 1,
    name: "Lisbon",
    country: "Portugal",
    region: "Europe",
    imageUrl: "/images/lisbon.png",
    escapeImageUrl: "/images/lisbon2.png",
    price: 450,
    flightTime: 2.5,
    sunshineHours: 9,
    exclusivity: "popular",
    description:
      "Lisbon offers consistently superior sunshine hours without the Mediterranean crowds. The city's refined culture and exceptional dining naturally attract those who appreciate... elevated standards. While others endure gray skies, you'll find the atmospheric conditions here rather... appropriate.",
    bestTimeToVisit: "April to October",
    currency: "Euro (€)",
    forecast: [
      { day: "Today", temp: 24, sunny: true, condition: "Sunny" },
      { day: "Tomorrow", temp: 25, sunny: true, condition: "Sunny" },
      { day: "Day 3", temp: 23, sunny: true, condition: "Partly Cloudy" },
    ],
    founderHistory: [
      'Series A founder who "needed to rethink product strategy"',
      'Unicorn CTO on a "technical research trip"',
      'VC partner conducting "market analysis"',
    ],
    workspaces: [
      { name: "Outsite Lisbon", type: "Co-working Space", wifiRating: 5 },
      { name: "Copenhagen Coffee Lab", type: "Café", wifiRating: 4 },
      { name: "Second Home Lisboa", type: "Premium Office", wifiRating: 5 },
    ],
    alibis: [
      "I'm exploring European expansion opportunities for Q3.",
      "Our Portuguese user base is growing, and I need to understand the market better.",
      "I've scheduled strategic meetings with potential EU partners.",
    ],
  },
  {
    id: 2,
    name: "Bali",
    country: "Indonesia",
    region: "Asia",
    imageUrl: "/images/bali.jpeg",
    escapeImageUrl: "/images/bali2.png",
    price: 800,
    flightTime: 7.5,
    sunshineHours: 10,
    exclusivity: "mainstream",
    description:
      "Bali's eternal summer and spiritual sophistication offer something beyond the typical tropical escape. The island's rice terraces and temple culture provide a backdrop that's... elevated. Of course, the wellness scene here attracts a more discerning crowd than your average beach destination.",
    bestTimeToVisit: "May to September",
    currency: "Indonesian Rupiah (Rp)",
    forecast: [
      { day: "Today", temp: 29, sunny: true, condition: "Sunny" },
      { day: "Tomorrow", temp: 30, sunny: true, condition: "Sunny" },
      { day: "Day 3", temp: 29, sunny: false, condition: "Scattered Showers" },
    ],
    founderHistory: [
      'Post-Series B founder on a "team building retreat" (solo)',
      'Bootstrapped SaaS founder "reconnecting with purpose"',
      'Crypto millionaire "establishing presence in Asian markets"',
    ],
    workspaces: [
      { name: "Outpost Ubud", type: "Co-working Space", wifiRating: 4 },
      { name: "Dojo Bali", type: "Co-working Space", wifiRating: 5 },
      { name: "Tropical Nomad", type: "Café", wifiRating: 3 },
    ],
    alibis: [
      "I'm researching emerging Asian markets for potential expansion.",
      "Our dev team in Southeast Asia needs on-site leadership for a sprint.",
      "I'm attending a private tech retreat with strategic partners.",
    ],
  },
  {
    id: 3,
    name: "Tulum",
    country: "Mexico",
    region: "Americas",
    imageUrl: "/images/tulum.png",
    escapeImageUrl: "/images/tulum2.png",
    price: 550,
    flightTime: 4.5,
    sunshineHours: 8,
    exclusivity: "popular",
    description:
      "Tulum's ancient Mayan ruins overlook Caribbean waters that maintain a rather... perfect temperature year-round. The cenotes and jungle luxury resorts attract those who appreciate history with their sunshine. Unlike Cancun's spring break atmosphere, this is where the sophisticated escape to.",
    bestTimeToVisit: "November to April",
    currency: "Mexican Peso (MXN)",
    forecast: [
      { day: "Today", temp: 27, sunny: true, condition: "Sunny" },
      { day: "Tomorrow", temp: 28, sunny: true, condition: "Sunny" },
      { day: "Day 3", temp: 26, sunny: false, condition: "Partly Cloudy" },
    ],
    founderHistory: [
      'Pre-IPO founder "finalizing strategic vision"',
      'Recently funded founder "recalibrating after fundraise"',
      'Tech executive "developing Latin American strategy"',
    ],
    workspaces: [
      { name: "Selina Tulum", type: "Co-working Space", wifiRating: 4 },
      { name: "Digital Jungle", type: "Beachfront Office", wifiRating: 3 },
      { name: "Papaya Playa Project", type: "Resort with Workspace", wifiRating: 4 },
    ],
    alibis: [
      "I'm meeting with our LATAM partners to discuss Q4 strategy.",
      "We're considering a Mexico office, and I need to evaluate the location.",
      "I've scheduled back-to-back meetings with potential investors in the region.",
    ],
  },
  {
    id: 4,
    name: "Mallorca",
    country: "Spain",
    region: "Europe",
    imageUrl: "/images/Mallorca.png",
    escapeImageUrl: "/images/Mallorca2.png",
    price: 380,
    flightTime: 2,
    sunshineHours: 7,
    exclusivity: "emerging",
    description:
      "Beyond the tourist areas, Mallorca offers sophisticated hideaways with Mediterranean charm that's... authentic. The island's coves and mountain villages provide the kind of refined escape that discerning travelers seek. Naturally, the weather here cooperates beautifully with such elevated tastes.",
    bestTimeToVisit: "May to October",
    currency: "Euro (€)",
    forecast: [
      { day: "Today", temp: 22, sunny: true, condition: "Sunny" },
      { day: "Tomorrow", temp: 23, sunny: true, condition: "Sunny" },
      { day: "Day 3", temp: 21, sunny: false, condition: "Cloudy" },
    ],
    founderHistory: [
      'Fintech founder "studying Mediterranean markets"',
      'Recently exited founder "contemplating next venture"',
      'VC partner "strengthening European network"',
    ],
    workspaces: [
      { name: "The Hub Mallorca", type: "Co-working Space", wifiRating: 5 },
      { name: "Santa Catalina", type: "Boutique Hotel with Workspace", wifiRating: 4 },
      { name: "Palma Spaces", type: "Private Office", wifiRating: 5 },
    ],
    alibis: [
      "I'm meeting with European investors to discuss our next funding round.",
      "Our EU compliance team needs in-person guidance for the new regulations.",
      "I'm conducting a competitive analysis of similar businesses in the region.",
    ],
  },
  {
    id: 5,
    name: "Cape Town",
    country: "South Africa",
    region: "Africa",
    imageUrl: "/images/capetown.png",
    escapeImageUrl: "/images/capetown2.png",
    price: 720,
    flightTime: 6,
    sunshineHours: 9,
    exclusivity: "undiscovered",
    description:
      "Cape Town's dramatic coastline enjoys sunshine that puts European summers to shame. The Winelands and sophisticated dining scene attract those who understand that both weather and wine require... proper standards. Table Mountain provides a rather spectacular backdrop for such refined pursuits.",
    bestTimeToVisit: "November to March",
    currency: "South African Rand (R)",
    forecast: [
      { day: "Today", temp: 25, sunny: true, condition: "Sunny" },
      { day: "Tomorrow", temp: 24, sunny: true, condition: "Sunny" },
      { day: "Day 3", temp: 26, sunny: true, condition: "Sunny" },
    ],
    founderHistory: [
      'Impact investor "exploring African opportunities"',
      'Tech founder "researching emerging markets"',
      'VC scout "identifying untapped talent"',
    ],
    workspaces: [
      { name: "Workshop17", type: "Co-working Space", wifiRating: 5 },
      { name: "Inner City Ideas Cartel", type: "Private Club", wifiRating: 5 },
      { name: "Truth Coffee", type: "Café", wifiRating: 4 },
    ],
    alibis: [
      "I'm exploring expansion opportunities in African markets.",
      "We're considering Cape Town for our next remote team retreat.",
      "I'm meeting with potential partners to discuss our global strategy.",
    ],
  },
  {
    id: 6,
    name: "Koh Samui",
    country: "Thailand",
    region: "Asia",
    imageUrl: "/images/kohsamui.png",
    escapeImageUrl: "/images/kohsamui2.png",
    price: 650,
    flightTime: 8,
    sunshineHours: 8,
    exclusivity: "emerging",
    description:
      "Koh Samui's pristine beaches and year-round warmth offer a more... civilized alternative to Thailand's backpacker trails. The island's luxury resorts and spa culture attract those who appreciate their tropical paradise with proper service. As you'd expect, the weather here is consistently... cooperative.",
    bestTimeToVisit: "December to April",
    currency: "Thai Baht (฿)",
    forecast: [
      { day: "Today", temp: 28, sunny: true, condition: "Sunny" },
      { day: "Tomorrow", temp: 29, sunny: false, condition: "Scattered Showers" },
      { day: "Day 3", temp: 28, sunny: true, condition: "Sunny" },
    ],
    founderHistory: [
      'Burned-out founder "reconnecting with vision"',
      'Post-acquisition executive "contemplating next venture"',
      'Angel investor "developing Asia strategy"',
    ],
    workspaces: [
      { name: "KoHub", type: "Co-working Space", wifiRating: 4 },
      { name: "The Workspace", type: "Beachfront Office", wifiRating: 3 },
      { name: "Library", type: "Luxury Hotel Workspace", wifiRating: 5 },
    ],
    alibis: [
      "I'm conducting market research in Southeast Asia for our expansion strategy.",
      "Our APAC team needs leadership presence for the quarter.",
      "I'm attending a private tech summit with strategic partners.",
    ],
  },
  // Adding the remaining destinations from coordinates-data.ts
  {
    id: 7,
    name: "Santorini",
    country: "Greece",
    region: "Europe",
    imageUrl: "/images/santorini1.jpg",
    escapeImageUrl: "/images/santorini2.jpg",
    price: 580,
    flightTime: 3.5,
    sunshineHours: 9,
    exclusivity: "popular",
    description:
      "Santorini's iconic white buildings and volcanic sunsets create a backdrop that's undeniably photogenic. The island's wine culture and clifftop dining attract those who understand that some views are worth the crowds. Naturally, the Aegean climate provides the kind of reliable sunshine that makes such indulgences possible.",
    bestTimeToVisit: "May to October",
    currency: "Euro (€)",
    forecast: [
      { day: "Today", temp: 24, sunny: true, condition: "Sunny" },
      { day: "Tomorrow", temp: 25, sunny: true, condition: "Sunny" },
      { day: "Day 3", temp: 26, sunny: true, condition: "Sunny" },
    ],
    founderHistory: [
      'Series B founder "contemplating company culture"',
      'Tech influencer "creating content strategy"',
      'VC partner "strengthening Mediterranean network"',
    ],
    workspaces: [
      { name: "Santorini Coworking", type: "Co-working Space", wifiRating: 4 },
      { name: "Theros Wave Bar", type: "Beach Office", wifiRating: 3 },
      { name: "Enigma Café", type: "Café", wifiRating: 4 },
    ],
    alibis: [
      "I'm meeting with potential European investors in a more relaxed setting.",
      "Our design team needed inspiration for our new brand aesthetic.",
      "I'm conducting user research with our Mediterranean customer base.",
    ],
  },
  {
    id: 8,
    name: "Cancun",
    country: "Mexico",
    region: "Americas",
    imageUrl: "/images/cancun1.png",
    escapeImageUrl: "/images/cancun2.png",
    price: 480,
    flightTime: 4,
    sunshineHours: 8,
    exclusivity: "mainstream",
    description:
      "While Cancun might be mainstream for spring breakers, the city's secluded luxury resorts offer something more... refined. The Mayan Riviera's turquoise waters and consistent warmth provide the kind of tropical perfection that discerning travelers seek. Of course, the right accommodations make all the difference.",
    bestTimeToVisit: "December to April",
    currency: "Mexican Peso (MXN)",
    forecast: [
      { day: "Today", temp: 29, sunny: true, condition: "Sunny" },
      { day: "Tomorrow", temp: 30, sunny: true, condition: "Sunny" },
      { day: "Day 3", temp: 28, sunny: false, condition: "Partly Cloudy" },
    ],
    founderHistory: [
      'Growth-stage CEO "finalizing go-to-market strategy"',
      'Tech executive "conducting leadership offsite" (solo)',
      'Startup founder "exploring LATAM expansion"',
    ],
    workspaces: [
      { name: "Selina Cancun", type: "Co-working Space", wifiRating: 4 },
      { name: "Nizuc Resort", type: "Luxury Workspace", wifiRating: 5 },
      { name: "Starbucks Hotel Zone", type: "Café", wifiRating: 3 },
    ],
    alibis: [
      "I'm meeting with potential distribution partners in Mexico.",
      "Our LATAM team requested an in-person strategy session.",
      "I'm conducting market research for our expansion plans.",
    ],
  },
  {
    id: 9,
    name: "Miami",
    country: "United States",
    region: "Americas",
    imageUrl: "/images/miami1.jpg",
    escapeImageUrl: "/images/miami2.jpeg",
    price: 520,
    flightTime: 3,
    sunshineHours: 9,
    exclusivity: "popular",
    description:
      "Miami has evolved beyond its party reputation into something more... sophisticated. The city's Art Deco architecture and emerging culinary scene provide culture with your sunshine. Naturally, South Beach's year-round warmth attracts those who appreciate both style and substance.",
    bestTimeToVisit: "November to April",
    currency: "US Dollar ($)",
    forecast: [
      { day: "Today", temp: 28, sunny: true, condition: "Sunny" },
      { day: "Tomorrow", temp: 29, sunny: true, condition: "Sunny" },
      { day: "Day 3", temp: 27, sunny: false, condition: "Partly Cloudy" },
    ],
    founderHistory: [
      'Crypto founder "establishing presence in emerging tech hub"',
      'VC partner "sourcing Miami deal flow"',
      'Tech CEO "evaluating East Coast headquarters"',
    ],
    workspaces: [
      { name: "The LAB Miami", type: "Co-working Space", wifiRating: 5 },
      { name: "Soho Beach House", type: "Members Club", wifiRating: 4 },
      { name: "Panther Coffee Wynwood", type: "Café", wifiRating: 4 },
    ],
    alibis: [
      "I'm meeting with East Coast investors to discuss our Series B.",
      "We're considering opening a Miami office to tap into the growing tech scene.",
      "I'm speaking at a private tech conference on innovation.",
    ],
  },
  {
    id: 10,
    name: "Dubai",
    country: "United Arab Emirates",
    region: "Asia",
    imageUrl: "/images/dubai1.png",
    escapeImageUrl: "/images/dubai2.png",
    price: 780,
    flightTime: 7,
    sunshineHours: 10,
    exclusivity: "emerging",
    description:
      "Dubai's gleaming towers and desert sunshine create an atmosphere of unapologetic luxury. The city's world-class dining and shopping attract those who understand that excess, when done properly, is an art form. As you'd expect, the weather here cooperates beautifully with such... elevated pursuits.",
    bestTimeToVisit: "November to March",
    currency: "UAE Dirham (AED)",
    forecast: [
      { day: "Today", temp: 32, sunny: true, condition: "Sunny" },
      { day: "Tomorrow", temp: 33, sunny: true, condition: "Sunny" },
      { day: "Day 3", temp: 34, sunny: true, condition: "Sunny" },
    ],
    founderHistory: [
      'Fintech founder "exploring Middle East expansion"',
      'Series C CEO "meeting with sovereign wealth funds"',
      'Tech executive "establishing strategic partnerships"',
    ],
    workspaces: [
      { name: "A4 Space", type: "Co-working Space", wifiRating: 5 },
      { name: "Jumeirah Beach Hotel", type: "Luxury Workspace", wifiRating: 5 },
      { name: "One&Only Royal Mirage", type: "Private Office", wifiRating: 5 },
    ],
    alibis: [
      "I'm meeting with potential investors from the Middle East.",
      "We're exploring expansion opportunities in the UAE and broader region.",
      "I'm attending an exclusive tech conference focused on emerging markets.",
    ],
  },
  {
    id: 11,
    name: "Maldives",
    country: "Maldives",
    region: "Asia",
    imageUrl: "/images/maldives1.png",
    escapeImageUrl: "/images/maldives2.png",
    price: 1200,
    flightTime: 10,
    sunshineHours: 8,
    exclusivity: "undiscovered",
    description:
      "The Maldives offers the ultimate in aquatic luxury—overwater bungalows where the only decision is which shade of turquoise to contemplate. The atolls' pristine isolation attracts those who understand that true luxury is... uninterrupted. Naturally, the weather here maintains a rather perfect consistency.",
    bestTimeToVisit: "December to April",
    currency: "Maldivian Rufiyaa (MVR)",
    forecast: [
      { day: "Today", temp: 30, sunny: true, condition: "Sunny" },
      { day: "Tomorrow", temp: 29, sunny: true, condition: "Sunny" },
      { day: "Day 3", temp: 30, sunny: false, condition: "Scattered Showers" },
    ],
    founderHistory: [
      'Post-exit founder "contemplating next venture"',
      'Unicorn CEO "recharging after fundraise"',
      'Tech executive "conducting deep strategic work"',
    ],
    workspaces: [
      { name: "Soneva Fushi", type: "Private Villa Office", wifiRating: 4 },
      { name: "Conrad Maldives", type: "Underwater Office", wifiRating: 3 },
      { name: "One&Only Reethi Rah", type: "Beach Workspace", wifiRating: 4 },
    ],
    alibis: [
      "I'm taking a strategic retreat to map out our five-year vision.",
      "I needed complete isolation to solve some complex product challenges.",
      "I'm conducting a personal leadership development intensive.",
    ],
  },
  {
    id: 12,
    name: "Phuket",
    country: "Thailand",
    region: "Asia",
    imageUrl: "/images/phuket1.png",
    escapeImageUrl: "/images/phuket2.png",
    price: 600,
    flightTime: 9,
    sunshineHours: 7,
    exclusivity: "mainstream",
    description:
      "Phuket's limestone cliffs and azure waters offer tropical luxury at prices that would make European resorts... envious. The island's spa culture and Thai cuisine attract those who appreciate refinement without the usual premium. Of course, the Andaman Sea's warmth makes such indulgences even more appealing.",
    bestTimeToVisit: "November to April",
    currency: "Thai Baht (฿)",
    forecast: [
      { day: "Today", temp: 29, sunny: true, condition: "Sunny" },
      { day: "Tomorrow", temp: 30, sunny: false, condition: "Scattered Showers" },
      { day: "Day 3", temp: 28, sunny: true, condition: "Sunny" },
    ],
    founderHistory: [
      'Bootstrapped founder "optimizing runway"',
      'Tech executive "researching remote work culture"',
      'Startup founder "establishing APAC connections"',
    ],
    workspaces: [
      { name: "Garage Society", type: "Co-working Space", wifiRating: 4 },
      { name: "Banyan Tree", type: "Resort Workspace", wifiRating: 4 },
      { name: "Blue Cafe", type: "Café", wifiRating: 3 },
    ],
    alibis: [
      "I'm conducting research on remote work best practices for our distributed team.",
      "Our APAC expansion requires on-the-ground market research.",
      "I'm meeting with potential manufacturing partners in Southeast Asia.",
    ],
  },
  {
    id: 13,
    name: "Ibiza",
    country: "Spain",
    region: "Europe",
    imageUrl: "/images/ibiza1.png",
    escapeImageUrl: "/images/ibiza2.png",
    price: 520,
    flightTime: 2.5,
    sunshineHours: 9,
    exclusivity: "popular",
    description:
      "Ibiza's reputation for hedonism masks a more... sophisticated side of pine-covered hills and crystalline coves. The island's sunset culture and Balearic cuisine attract those who appreciate their revelry with proper style. Naturally, the Mediterranean climate provides the perfect backdrop for such refined pursuits.",
    bestTimeToVisit: "May to October",
    currency: "Euro (€)",
    forecast: [
      { day: "Today", temp: 26, sunny: true, condition: "Sunny" },
      { day: "Tomorrow", temp: 27, sunny: true, condition: "Sunny" },
      { day: "Day 3", temp: 25, sunny: true, condition: "Sunny" },
    ],
    founderHistory: [
      'Tech CEO "hosting leadership offsite"',
      'VC partner "strengthening founder network"',
      'Series B founder "researching European market"',
    ],
    workspaces: [
      { name: "Coworking Ibiza", type: "Co-working Space", wifiRating: 4 },
      { name: "Cotton Beach Club", type: "Beach Office", wifiRating: 3 },
      { name: "Nobu Hotel", type: "Luxury Workspace", wifiRating: 5 },
    ],
    alibis: [
      "I'm hosting a strategic retreat for our executive team.",
      "I'm meeting with several European investors who happen to be on the island.",
      "I'm researching wellness programs for our company's mental health initiative.",
    ],
  },
  {
    id: 14,
    name: "Maui",
    country: "United States",
    region: "Americas",
    imageUrl: "/images/maui.png",
    escapeImageUrl: "/images/maui2.png",
    price: 850,
    flightTime: 6,
    sunshineHours: 8,
    exclusivity: "emerging",
    description:
      "Maui's volcanic landscapes and Pacific sunsets create a backdrop that's... cinematically perfect. The island's farm-to-table cuisine and luxury resorts attract those who appreciate their tropical paradise with proper sophistication. As you'd expect, the Hawaiian climate maintains a rather enviable consistency.",
    bestTimeToVisit: "April to October",
    currency: "US Dollar ($)",
    forecast: [
      { day: "Today", temp: 27, sunny: true, condition: "Sunny" },
      { day: "Tomorrow", temp: 28, sunny: true, condition: "Sunny" },
      { day: "Day 3", temp: 26, sunny: false, condition: "Partly Cloudy" },
    ],
    founderHistory: [
      'Tech CEO "conducting West Coast investor meetings"',
      'Post-acquisition founder "developing new venture concepts"',
      'VC partner "hosting portfolio company retreat"',
    ],
    workspaces: [
      { name: "Wailea Beach Resort", type: "Luxury Workspace", wifiRating: 5 },
      { name: "Maui Tech Hub", type: "Co-working Space", wifiRating: 4 },
      { name: "Four Seasons", type: "Private Office", wifiRating: 5 },
    ],
    alibis: [
      "I'm meeting with several West Coast investors who are vacationing on the island.",
      "We're considering Hawaii for our annual company retreat and I'm scouting locations.",
      "I'm working on our strategic plan for next year and needed space to think.",
    ],
  },
  {
    id: 15,
    name: "Rio de Janeiro",
    country: "Brazil",
    region: "Americas",
    imageUrl: "/images/rio1.jpeg",
    escapeImageUrl: "/images/rio2.jpg",
    price: 680,
    flightTime: 9.5,
    sunshineHours: 7,
    exclusivity: "emerging",
    description:
      "Rio's dramatic coastline and Carnival spirit create an atmosphere of unapologetic celebration. The city's beach culture and vibrant nightlife attract those who understand that sophistication sometimes requires... a certain joie de vivre. Naturally, Ipanema's year-round warmth makes such pursuits infinitely more appealing.",
    bestTimeToVisit: "December to March",
    currency: "Brazilian Real (R$)",
    forecast: [
      { day: "Today", temp: 28, sunny: true, condition: "Sunny" },
      { day: "Tomorrow", temp: 29, sunny: true, condition: "Sunny" },
      { day: "Day 3", temp: 27, sunny: false, condition: "Partly Cloudy" },
    ],
    founderHistory: [
      'Tech entrepreneur "exploring LATAM opportunities"',
      'VC partner "building relationships with Brazilian startups"',
      'Series A founder "researching expansion to South America"',
    ],
    workspaces: [
      { name: "Nex Coworking", type: "Co-working Space", wifiRating: 4 },
      { name: "Fasano Rio", type: "Luxury Hotel Workspace", wifiRating: 5 },
      { name: "Sofitel Ipanema", type: "Beach View Office", wifiRating: 4 },
    ],
    alibis: [
      "I'm meeting with potential partners for our Latin American expansion.",
      "We're considering opening a development office in Brazil to tap into local talent.",
      "I'm conducting market research for our product localization strategy.",
    ],
  },
  {
    id: 16,
    name: "Marrakech",
    country: "Morocco",
    region: "Africa",
    imageUrl: "/images/marrakech1.jpg",
    escapeImageUrl: "/images/marrakech2.jpeg",
    price: 450,
    flightTime: 3.5,
    sunshineHours: 9,
    exclusivity: "undiscovered",
    description:
      "Marrakech's ancient medina and Atlas Mountain backdrop create an exotic sophistication that's... intoxicating. The city's riad culture and spice-laden cuisine attract those who appreciate their luxury with a touch of adventure. Of course, the Moroccan sun provides the perfect warmth for such atmospheric indulgences.",
    bestTimeToVisit: "March to May, September to November",
    currency: "Moroccan Dirham (MAD)",
    forecast: [
      { day: "Today", temp: 28, sunny: true, condition: "Sunny" },
      { day: "Tomorrow", temp: 29, sunny: true, condition: "Sunny" },
      { day: "Day 3", temp: 30, sunny: true, condition: "Sunny" },
    ],
    founderHistory: [
      'Creative agency founder "seeking design inspiration"',
      'Tech CEO "exploring African market opportunities"',
      'VC partner "connecting with North African startups"',
    ],
    workspaces: [
      { name: "The Spot", type: "Co-working Space", wifiRating: 4 },
      { name: "La Mamounia", type: "Luxury Hotel Workspace", wifiRating: 5 },
      { name: "Royal Mansour", type: "Private Riad Office", wifiRating: 5 },
    ],
    alibis: [
      "I'm researching emerging markets in North Africa for potential expansion.",
      "Our design team needed authentic inspiration for our new product line.",
      "I'm meeting with potential partners to discuss our global strategy.",
    ],
  },
  {
    id: 17,
    name: "Sydney",
    country: "Australia",
    region: "Oceania",
    imageUrl: "/images/sydney.png",
    escapeImageUrl: "/images/sydney2.png",
    price: 950,
    flightTime: 14,
    sunshineHours: 7,
    exclusivity: "emerging",
    description:
      "Sydney's harbor views and cosmopolitan energy create an atmosphere that's both sophisticated and... refreshingly unpretentious. The city's coffee culture and coastal lifestyle attract those who appreciate their urban sophistication with a beach backdrop. Naturally, the Southern Hemisphere's seasons provide a delightful escape from northern winters.",
    bestTimeToVisit: "November to March",
    currency: "Australian Dollar (A$)",
    forecast: [
      { day: "Today", temp: 24, sunny: true, condition: "Sunny" },
      { day: "Tomorrow", temp: 25, sunny: true, condition: "Sunny" },
      { day: "Day 3", temp: 23, sunny: false, condition: "Partly Cloudy" },
    ],
    founderHistory: [
      'Tech CEO "exploring APAC headquarters location"',
      'Series B founder "meeting with Australian investors"',
      'Product executive "researching APAC user preferences"',
    ],
    workspaces: [
      { name: "Fishburners", type: "Co-working Space", wifiRating: 5 },
      { name: "The Old Clare Hotel", type: "Boutique Workspace", wifiRating: 4 },
      { name: "Park Hyatt Sydney", type: "Luxury Office", wifiRating: 5 },
    ],
    alibis: [
      "I'm meeting with potential investors and partners in the APAC region.",
      "We're considering Sydney for our Asia-Pacific headquarters.",
      "I'm conducting user research with our Australian customer base.",
    ],
  },
  {
    id: 18,
    name: "Amalfi Coast",
    country: "Italy",
    region: "Europe",
    imageUrl: "/images/amalfi1.png",
    escapeImageUrl: "/images/amalfi2.png",
    price: 680,
    flightTime: 2.5,
    sunshineHours: 8,
    exclusivity: "undiscovered",
    description:
      "The Amalfi Coast's dramatic cliffs and lemon-scented terraces create a sophistication that's... timelessly Italian. The region's coastal cuisine and boutique hotels attract those who understand that luxury is best served with a view. As you'd expect, the Mediterranean climate provides the perfect accompaniment to such refined pleasures.",
    bestTimeToVisit: "May to September",
    currency: "Euro (€)",
    forecast: [
      { day: "Today", temp: 25, sunny: true, condition: "Sunny" },
      { day: "Tomorrow", temp: 26, sunny: true, condition: "Sunny" },
      { day: "Day 3", temp: 24, sunny: true, condition: "Sunny" },
    ],
    founderHistory: [
      'Luxury brand CEO "researching Italian craftsmanship"',
      'Design-focused founder "seeking aesthetic inspiration"',
      'Tech executive "hosting exclusive leadership retreat"',
    ],
    workspaces: [
      { name: "Villa Cimbrone", type: "Garden Workspace", wifiRating: 3 },
      { name: "Hotel Santa Caterina", type: "Seaside Office", wifiRating: 4 },
      { name: "Le Sirenuse", type: "Luxury Workspace", wifiRating: 4 },
    ],
    alibis: [
      "I'm meeting with potential European luxury partners for our premium product line.",
      "Our design team needed authentic Mediterranean inspiration.",
      "I'm hosting a strategic retreat for our executive leadership team.",
    ],
  },
  {
    id: 19,
    name: "Seychelles",
    country: "Seychelles",
    region: "Africa",
    imageUrl: "/placeholder.svg?height=600&width=800&text=Seychelles",
    escapeImageUrl: "/placeholder.svg?height=600&width=800&text=Seychelles+Beach",
    price: 1100,
    flightTime: 9,
    sunshineHours: 8,
    exclusivity: "undiscovered",
    description:
      "The Seychelles' granite boulders and powder-soft beaches create an island paradise that's... refreshingly exclusive. The archipelago's conservation ethos and luxury eco-resorts attract those who appreciate their indulgence with environmental consciousness. Naturally, the equatorial climate maintains a rather perfect tropical consistency.",
    bestTimeToVisit: "April to May, October to November",
    currency: "Seychellois Rupee (SCR)",
    forecast: [
      { day: "Today", temp: 29, sunny: true, condition: "Sunny" },
      { day: "Tomorrow", temp: 28, sunny: true, condition: "Sunny" },
      { day: "Day 3", temp: 29, sunny: false, condition: "Scattered Showers" },
    ],
    founderHistory: [
      'Post-exit founder "contemplating next venture"',
      'Tech CEO "conducting deep strategic planning"',
      'VC partner "recharging between fund cycles"',
    ],
    workspaces: [
      { name: "Four Seasons", type: "Private Villa Office", wifiRating: 4 },
      { name: "North Island Lodge", type: "Exclusive Workspace", wifiRating: 3 },
      { name: "Six Senses Zil Pasyon", type: "Ocean View Office", wifiRating: 4 },
    ],
    alibis: [
      "I needed complete isolation to solve some complex strategic challenges.",
      "I'm taking a brief executive retreat to map our five-year vision.",
      "I'm conducting research on sustainable tourism for our ESG initiatives.",
    ],
  },
  {
    id: 20,
    name: "Bora Bora",
    country: "French Polynesia",
    region: "Oceania",
    imageUrl: "/placeholder.svg?height=600&width=800&text=Bora+Bora",
    escapeImageUrl: "/placeholder.svg?height=600&width=800&text=Bora+Bora+Beach",
    price: 1500,
    flightTime: 12,
    sunshineHours: 7,
    exclusivity: "undiscovered",
    description:
      "Bora Bora's emerald peaks and lagoon of impossible blue create the ultimate expression of Polynesian luxury. The island's overwater bungalows and pearl farms attract those who understand that paradise, when properly curated, requires no compromise. Of course, the South Pacific climate maintains a tropical perfection that's... utterly reliable.",
    bestTimeToVisit: "May to October",
    currency: "CFP Franc (XPF)",
    forecast: [
      { day: "Today", temp: 28, sunny: true, condition: "Sunny" },
      { day: "Tomorrow", temp: 29, sunny: true, condition: "Sunny" },
      { day: "Day 3", temp: 28, sunny: false, condition: "Scattered Showers" },
    ],
    founderHistory: [
      'Unicorn CEO "recharging after major funding round"',
      'Tech executive "developing long-term company vision"',
      'Serial entrepreneur "incubating new venture concepts"',
    ],
    workspaces: [
      { name: "Four Seasons", type: "Overwater Office", wifiRating: 4 },
      { name: "St. Regis", type: "Private Villa Workspace", wifiRating: 4 },
      { name: "Conrad Bora Bora", type: "Beachfront Office", wifiRating: 3 },
    ],
    alibis: [
      "I'm taking a strategic thinking retreat to map our next five years.",
      "I needed complete isolation to solve some complex product challenges.",
      "I'm conducting research on remote work effectiveness in different environments.",
    ],
  },
]
