import type { City } from "./types"

// Sample data for the destinations page
export const cities: City[] = [
  {
    id: 1,
    name: "Lisbon",
    country: "Portugal",
    region: "Europe",
    imageUrl: "/images/lisbon.png",
    escapeImageUrl: "/images/lisbon2.png",
    price: 450,
    flightTime: 2.5,
    sunshineHours: 9,
    exclusivity: "popular",
    description:
      "Historic charm meets modern amenities in Lisbon. With reliable Wi-Fi throughout the city and a growing tech scene, it's perfect for pretending to work while enjoying pastéis de nata and ocean views.",
    bestTimeToVisit: "April to October",
    currency: "Euro (€)",
    forecast: [
      { day: "Today", temp: 24, sunny: true, condition: "Sunny" },
      { day: "Tomorrow", temp: 25, sunny: true, condition: "Sunny" },
      { day: "Day 3", temp: 23, sunny: true, condition: "Partly Cloudy" },
    ],
    founderHistory: [
      'Series A founder who "needed to rethink product strategy"',
      'Unicorn CTO on a "technical research trip"',
      'VC partner conducting "market analysis"',
    ],
    workspaces: [
      { name: "Outsite Lisbon", type: "Co-working Space", wifiRating: 5 },
      { name: "Copenhagen Coffee Lab", type: "Café", wifiRating: 4 },
      { name: "Second Home Lisboa", type: "Premium Office", wifiRating: 5 },
    ],
    alibis: [
      "I'm exploring European expansion opportunities for Q3.",
      "Our Portuguese user base is growing, and I need to understand the market better.",
      "I've scheduled strategic meetings with potential EU partners.",
    ],
  },
  {
    id: 2,
    name: "Bali",
    country: "Indonesia",
    region: "Asia",
    imageUrl: "/images/bali.jpeg",
    escapeImageUrl: "/images/bali2.png",
    price: 800,
    flightTime: 7.5,
    sunshineHours: 10,
    exclusivity: "mainstream",
    description:
      "Once a secret haven, Bali now combines spiritual energy with high-speed internet. Perfect for those 'deep work' sessions that somehow always happen near a beach.",
    bestTimeToVisit: "May to September",
    currency: "Indonesian Rupiah (Rp)",
    forecast: [
      { day: "Today", temp: 29, sunny: true, condition: "Sunny" },
      { day: "Tomorrow", temp: 30, sunny: true, condition: "Sunny" },
      { day: "Day 3", temp: 29, sunny: false, condition: "Scattered Showers" },
    ],
    founderHistory: [
      'Post-Series B founder on a "team building retreat" (solo)',
      'Bootstrapped SaaS founder "reconnecting with purpose"',
      'Crypto millionaire "establishing presence in Asian markets"',
    ],
    workspaces: [
      { name: "Outpost Ubud", type: "Co-working Space", wifiRating: 4 },
      { name: "Dojo Bali", type: "Co-working Space", wifiRating: 5 },
      { name: "Tropical Nomad", type: "Café", wifiRating: 3 },
    ],
    alibis: [
      "I'm researching emerging Asian markets for potential expansion.",
      "Our dev team in Southeast Asia needs on-site leadership for a sprint.",
      "I'm attending a private tech retreat with strategic partners.",
    ],
  },
  {
    id: 3,
    name: "Tulum",
    country: "Mexico",
    region: "Americas",
    imageUrl: "/images/tulum.png",
    escapeImageUrl: "/images/tulum2.png",
    price: 550,
    flightTime: 4.5,
    sunshineHours: 8,
    exclusivity: "popular",
    description:
      "Tulum's beachfront 'offices' offer excellent backdrops for those rare video calls you can't reschedule, while the proximity to the US makes it easy to claim you're 'just a short flight away'.",
    bestTimeToVisit: "November to April",
    currency: "Mexican Peso (MXN)",
    forecast: [
      { day: "Today", temp: 27, sunny: true, condition: "Sunny" },
      { day: "Tomorrow", temp: 28, sunny: true, condition: "Sunny" },
      { day: "Day 3", temp: 26, sunny: false, condition: "Partly Cloudy" },
    ],
    founderHistory: [
      'Pre-IPO founder "finalizing strategic vision"',
      'Recently funded founder "recalibrating after fundraise"',
      'Tech executive "developing Latin American strategy"',
    ],
    workspaces: [
      { name: "Selina Tulum", type: "Co-working Space", wifiRating: 4 },
      { name: "Digital Jungle", type: "Beachfront Office", wifiRating: 3 },
      { name: "Papaya Playa Project", type: "Resort with Workspace", wifiRating: 4 },
    ],
    alibis: [
      "I'm meeting with our LATAM partners to discuss Q4 strategy.",
      "We're considering a Mexico office, and I need to evaluate the location.",
      "I've scheduled back-to-back meetings with potential investors in the region.",
    ],
  },
  {
    id: 4,
    name: "Mallorca",
    country: "Spain",
    region: "Europe",
    imageUrl: "/images/Mallorca.png",
    escapeImageUrl: "/images/Mallorca2.png",
    price: 380,
    flightTime: 2,
    sunshineHours: 7,
    exclusivity: "emerging",
    description:
      "Beyond the tourist areas, Mallorca offers sophisticated hideaways with Mediterranean charm and excellent connectivity. Take investor calls with a backdrop that subtly communicates success.",
    bestTimeToVisit: "May to October",
    currency: "Euro (€)",
    forecast: [
      { day: "Today", temp: 22, sunny: true, condition: "Sunny" },
      { day: "Tomorrow", temp: 23, sunny: true, condition: "Sunny" },
      { day: "Day 3", temp: 21, sunny: false, condition: "Cloudy" },
    ],
    founderHistory: [
      'Fintech founder "studying Mediterranean markets"',
      'Recently exited founder "contemplating next venture"',
      'VC partner "strengthening European network"',
    ],
    workspaces: [
      { name: "The Hub Mallorca", type: "Co-working Space", wifiRating: 5 },
      { name: "Santa Catalina", type: "Boutique Hotel with Workspace", wifiRating: 4 },
      { name: "Palma Spaces", type: "Private Office", wifiRating: 5 },
    ],
    alibis: [
      "I'm meeting with European investors to discuss our next funding round.",
      "Our EU compliance team needs in-person guidance for the new regulations.",
      "I'm conducting a competitive analysis of similar businesses in the region.",
    ],
  },
  {
    id: 5,
    name: "Cape Town",
    country: "South Africa",
    region: "Africa",
    imageUrl: "/images/capetown.png",
    escapeImageUrl: "/images/capetown2.png",
    price: 720,
    flightTime: 6,
    sunshineHours: 9,
    exclusivity: "undiscovered",
    description:
      "Cape Town's significant time zone difference provides the perfect excuse for delayed responses, while the emerging tech scene gives credibility to your 'market research' claims.",
    bestTimeToVisit: "November to March",
    currency: "South African Rand (R)",
    forecast: [
      { day: "Today", temp: 25, sunny: true, condition: "Sunny" },
      { day: "Tomorrow", temp: 24, sunny: true, condition: "Sunny" },
      { day: "Day 3", temp: 26, sunny: true, condition: "Sunny" },
    ],
    founderHistory: [
      'Impact investor "exploring African opportunities"',
      'Tech founder "researching emerging markets"',
      'VC scout "identifying untapped talent"',
    ],
    workspaces: [
      { name: "Workshop17", type: "Co-working Space", wifiRating: 5 },
      { name: "Inner City Ideas Cartel", type: "Private Club", wifiRating: 5 },
      { name: "Truth Coffee", type: "Café", wifiRating: 4 },
    ],
    alibis: [
      "I'm exploring expansion opportunities in African markets.",
      "We're considering Cape Town for our next remote team retreat.",
      "I'm meeting with potential partners to discuss our global strategy.",
    ],
  },
  {
    id: 6,
    name: "Koh Samui",
    country: "Thailand",
    region: "Asia",
    imageUrl: "/images/kohsamui.png",
    escapeImageUrl: "/images/kohsamui2.png",
    price: 650,
    flightTime: 8,
    sunshineHours: 8,
    exclusivity: "emerging",
    description:
      "Koh Samui offers excellent infrastructure for remote work, with the added benefit of being far enough away that no one expects you to be available during their working hours.",
    bestTimeToVisit: "December to April",
    currency: "Thai Baht (฿)",
    forecast: [
      { day: "Today", temp: 28, sunny: true, condition: "Sunny" },
      { day: "Tomorrow", temp: 29, sunny: false, condition: "Scattered Showers" },
      { day: "Day 3", temp: 28, sunny: true, condition: "Sunny" },
    ],
    founderHistory: [
      'Burned-out founder "reconnecting with vision"',
      'Post-acquisition executive "contemplating next venture"',
      'Angel investor "developing Asia strategy"',
    ],
    workspaces: [
      { name: "KoHub", type: "Co-working Space", wifiRating: 4 },
      { name: "The Workspace", type: "Beachfront Office", wifiRating: 3 },
      { name: "Library", type: "Luxury Hotel Workspace", wifiRating: 5 },
    ],
    alibis: [
      "I'm conducting market research in Southeast Asia for our expansion strategy.",
      "Our APAC team needs leadership presence for the quarter.",
      "I'm attending a private tech summit with strategic partners.",
    ],
  },
  // Adding the remaining destinations from coordinates-data.ts
  {
    id: 7,
    name: "Santorini",
    country: "Greece",
    region: "Europe",
    imageUrl: "/images/santorini1.jpg",
    escapeImageUrl: "/images/santorini2.jpg",
    price: 580,
    flightTime: 3.5,
    sunshineHours: 9,
    exclusivity: "popular",
    description:
      "Santorini's iconic white buildings and blue domes provide the perfect backdrop for your 'strategic planning' Instagram stories. The island's high-end accommodations and reliable connectivity make it easy to maintain the illusion of productivity.",
    bestTimeToVisit: "May to October",
    currency: "Euro (€)",
    forecast: [
      { day: "Today", temp: 24, sunny: true, condition: "Sunny" },
      { day: "Tomorrow", temp: 25, sunny: true, condition: "Sunny" },
      { day: "Day 3", temp: 26, sunny: true, condition: "Sunny" },
    ],
    founderHistory: [
      'Series B founder "contemplating company culture"',
      'Tech influencer "creating content strategy"',
      'VC partner "strengthening Mediterranean network"',
    ],
    workspaces: [
      { name: "Santorini Coworking", type: "Co-working Space", wifiRating: 4 },
      { name: "Theros Wave Bar", type: "Beach Office", wifiRating: 3 },
      { name: "Enigma Café", type: "Café", wifiRating: 4 },
    ],
    alibis: [
      "I'm meeting with potential European investors in a more relaxed setting.",
      "Our design team needed inspiration for our new brand aesthetic.",
      "I'm conducting user research with our Mediterranean customer base.",
    ],
  },
  {
    id: 8,
    name: "Cancun",
    country: "Mexico",
    region: "Americas",
    imageUrl: "/images/cancun1.png",
    escapeImageUrl: "/images/cancun2.png",
    price: 480,
    flightTime: 4,
    sunshineHours: 8,
    exclusivity: "mainstream",
    description:
      "While Cancun might be mainstream for vacationers, the city offers secluded luxury resorts where founders can 'strategize' in peace. The proximity to the US makes it easy to claim you can 'be back for that meeting if needed' (though you never will be).",
    bestTimeToVisit: "December to April",
    currency: "Mexican Peso (MXN)",
    forecast: [
      { day: "Today", temp: 29, sunny: true, condition: "Sunny" },
      { day: "Tomorrow", temp: 30, sunny: true, condition: "Sunny" },
      { day: "Day 3", temp: 28, sunny: false, condition: "Partly Cloudy" },
    ],
    founderHistory: [
      'Growth-stage CEO "finalizing go-to-market strategy"',
      'Tech executive "conducting leadership offsite" (solo)',
      'Startup founder "exploring LATAM expansion"',
    ],
    workspaces: [
      { name: "Selina Cancun", type: "Co-working Space", wifiRating: 4 },
      { name: "Nizuc Resort", type: "Luxury Workspace", wifiRating: 5 },
      { name: "Starbucks Hotel Zone", type: "Café", wifiRating: 3 },
    ],
    alibis: [
      "I'm meeting with potential distribution partners in Mexico.",
      "Our LATAM team requested an in-person strategy session.",
      "I'm conducting market research for our expansion plans.",
    ],
  },
  {
    id: 9,
    name: "Miami",
    country: "United States",
    region: "Americas",
    imageUrl: "/images/miami1.jpg",
    escapeImageUrl: "/images/miami2.jpeg",
    price: 520,
    flightTime: 3,
    sunshineHours: 9,
    exclusivity: "popular",
    description:
      "Miami has reinvented itself as a tech hub, providing the perfect cover for your sunshine escape. Claim you're 'networking with crypto investors' while actually networking with bartenders at South Beach. The growing startup scene makes your presence there almost legitimate.",
    bestTimeToVisit: "November to April",
    currency: "US Dollar ($)",
    forecast: [
      { day: "Today", temp: 28, sunny: true, condition: "Sunny" },
      { day: "Tomorrow", temp: 29, sunny: true, condition: "Sunny" },
      { day: "Day 3", temp: 27, sunny: false, condition: "Partly Cloudy" },
    ],
    founderHistory: [
      'Crypto founder "establishing presence in emerging tech hub"',
      'VC partner "sourcing Miami deal flow"',
      'Tech CEO "evaluating East Coast headquarters"',
    ],
    workspaces: [
      { name: "The LAB Miami", type: "Co-working Space", wifiRating: 5 },
      { name: "Soho Beach House", type: "Members Club", wifiRating: 4 },
      { name: "Panther Coffee Wynwood", type: "Café", wifiRating: 4 },
    ],
    alibis: [
      "I'm meeting with East Coast investors to discuss our Series B.",
      "We're considering opening a Miami office to tap into the growing tech scene.",
      "I'm speaking at a private tech conference on innovation.",
    ],
  },
  {
    id: 10,
    name: "Dubai",
    country: "United Arab Emirates",
    region: "Asia",
    imageUrl: "/images/dubai1.png",
    escapeImageUrl: "/images/dubai2.png",
    price: 780,
    flightTime: 7,
    sunshineHours: 10,
    exclusivity: "emerging",
    description:
      "Dubai's reputation as a business hub makes it the perfect destination for founders seeking sunshine without suspicion. The city's luxury hotels offer excellent 'conference facilities' (poolside cabanas) and the time zone difference provides plausible deniability for missed calls.",
    bestTimeToVisit: "November to March",
    currency: "UAE Dirham (AED)",
    forecast: [
      { day: "Today", temp: 32, sunny: true, condition: "Sunny" },
      { day: "Tomorrow", temp: 33, sunny: true, condition: "Sunny" },
      { day: "Day 3", temp: 34, sunny: true, condition: "Sunny" },
    ],
    founderHistory: [
      'Fintech founder "exploring Middle East expansion"',
      'Series C CEO "meeting with sovereign wealth funds"',
      'Tech executive "establishing strategic partnerships"',
    ],
    workspaces: [
      { name: "A4 Space", type: "Co-working Space", wifiRating: 5 },
      { name: "Jumeirah Beach Hotel", type: "Luxury Workspace", wifiRating: 5 },
      { name: "One&Only Royal Mirage", type: "Private Office", wifiRating: 5 },
    ],
    alibis: [
      "I'm meeting with potential investors from the Middle East.",
      "We're exploring expansion opportunities in the UAE and broader region.",
      "I'm attending an exclusive tech conference focused on emerging markets.",
    ],
  },
  {
    id: 11,
    name: "Maldives",
    country: "Maldives",
    region: "Asia",
    imageUrl: "/images/maldives1.png",
    escapeImageUrl: "/images/maldives2.png",
    price: 1200,
    flightTime: 10,
    sunshineHours: 8,
    exclusivity: "undiscovered",
    description:
      "The Maldives offers the ultimate in founder seclusion. Claim you're 'going off-grid to focus on strategic planning' while actually going off-grid to focus on absolutely nothing. The limited connectivity provides the perfect excuse for delayed responses to all stakeholders.",
    bestTimeToVisit: "December to April",
    currency: "Maldivian Rufiyaa (MVR)",
    forecast: [
      { day: "Today", temp: 30, sunny: true, condition: "Sunny" },
      { day: "Tomorrow", temp: 29, sunny: true, condition: "Sunny" },
      { day: "Day 3", temp: 30, sunny: false, condition: "Scattered Showers" },
    ],
    founderHistory: [
      'Post-exit founder "contemplating next venture"',
      'Unicorn CEO "recharging after fundraise"',
      'Tech executive "conducting deep strategic work"',
    ],
    workspaces: [
      { name: "Soneva Fushi", type: "Private Villa Office", wifiRating: 4 },
      { name: "Conrad Maldives", type: "Underwater Office", wifiRating: 3 },
      { name: "One&Only Reethi Rah", type: "Beach Workspace", wifiRating: 4 },
    ],
    alibis: [
      "I'm taking a strategic retreat to map out our five-year vision.",
      "I needed complete isolation to solve some complex product challenges.",
      "I'm conducting a personal leadership development intensive.",
    ],
  },
  {
    id: 12,
    name: "Phuket",
    country: "Thailand",
    region: "Asia",
    imageUrl: "/images/phuket1.png",
    escapeImageUrl: "/images/phuket2.png",
    price: 600,
    flightTime: 9,
    sunshineHours: 7,
    exclusivity: "mainstream",
    description:
      "Phuket offers luxury at a fraction of Western prices, making it perfect for the cost-conscious founder who still wants to maintain appearances. The island's growing digital nomad scene provides cover for your 'remote work research trip' that involves more massages than meetings.",
    bestTimeToVisit: "November to April",
    currency: "Thai Baht (฿)",
    forecast: [
      { day: "Today", temp: 29, sunny: true, condition: "Sunny" },
      { day: "Tomorrow", temp: 30, sunny: false, condition: "Scattered Showers" },
      { day: "Day 3", temp: 28, sunny: true, condition: "Sunny" },
    ],
    founderHistory: [
      'Bootstrapped founder "optimizing runway"',
      'Tech executive "researching remote work culture"',
      'Startup founder "establishing APAC connections"',
    ],
    workspaces: [
      { name: "Garage Society", type: "Co-working Space", wifiRating: 4 },
      { name: "Banyan Tree", type: "Resort Workspace", wifiRating: 4 },
      { name: "Blue Cafe", type: "Café", wifiRating: 3 },
    ],
    alibis: [
      "I'm conducting research on remote work best practices for our distributed team.",
      "Our APAC expansion requires on-the-ground market research.",
      "I'm meeting with potential manufacturing partners in Southeast Asia.",
    ],
  },
  {
    id: 13,
    name: "Ibiza",
    country: "Spain",
    region: "Europe",
    imageUrl: "/images/ibiza1.png",
    escapeImageUrl: "/images/ibiza2.png",
    price: 520,
    flightTime: 2.5,
    sunshineHours: 9,
    exclusivity: "popular",
    description:
      "Ibiza isn't just for partying—it's for 'high-level networking' and 'relationship building' with other founders who are also definitely working and not partying. The island's growing wellness scene provides cover for your 'executive retreat' that happens to coincide with peak season.",
    bestTimeToVisit: "May to October",
    currency: "Euro (€)",
    forecast: [
      { day: "Today", temp: 26, sunny: true, condition: "Sunny" },
      { day: "Tomorrow", temp: 27, sunny: true, condition: "Sunny" },
      { day: "Day 3", temp: 25, sunny: true, condition: "Sunny" },
    ],
    founderHistory: [
      'Tech CEO "hosting leadership offsite"',
      'VC partner "strengthening founder network"',
      'Series B founder "researching European market"',
    ],
    workspaces: [
      { name: "Coworking Ibiza", type: "Co-working Space", wifiRating: 4 },
      { name: "Cotton Beach Club", type: "Beach Office", wifiRating: 3 },
      { name: "Nobu Hotel", type: "Luxury Workspace", wifiRating: 5 },
    ],
    alibis: [
      "I'm hosting a strategic retreat for our executive team.",
      "I'm meeting with several European investors who happen to be on the island.",
      "I'm researching wellness programs for our company's mental health initiative.",
    ],
  },
  {
    id: 14,
    name: "Maui",
    country: "United States",
    region: "Americas",
    imageUrl: "/images/maui.png",
    escapeImageUrl: "/images/maui2.png",
    price: 850,
    flightTime: 6,
    sunshineHours: 8,
    exclusivity: "emerging",
    description:
      "Maui offers the perfect blend of luxury and legitimacy for the discerning founder. Claim you're 'meeting with West Coast investors' while actually meeting with your surfing instructor. The Hawaii time zone provides plausible deniability for your limited availability.",
    bestTimeToVisit: "April to October",
    currency: "US Dollar ($)",
    forecast: [
      { day: "Today", temp: 27, sunny: true, condition: "Sunny" },
      { day: "Tomorrow", temp: 28, sunny: true, condition: "Sunny" },
      { day: "Day 3", temp: 26, sunny: false, condition: "Partly Cloudy" },
    ],
    founderHistory: [
      'Tech CEO "conducting West Coast investor meetings"',
      'Post-acquisition founder "developing new venture concepts"',
      'VC partner "hosting portfolio company retreat"',
    ],
    workspaces: [
      { name: "Wailea Beach Resort", type: "Luxury Workspace", wifiRating: 5 },
      { name: "Maui Tech Hub", type: "Co-working Space", wifiRating: 4 },
      { name: "Four Seasons", type: "Private Office", wifiRating: 5 },
    ],
    alibis: [
      "I'm meeting with several West Coast investors who are vacationing on the island.",
      "We're considering Hawaii for our annual company retreat and I'm scouting locations.",
      "I'm working on our strategic plan for next year and needed space to think.",
    ],
  },
  {
    id: 15,
    name: "Rio de Janeiro",
    country: "Brazil",
    region: "Americas",
    imageUrl: "/images/rio1.jpeg",
    escapeImageUrl: "/images/rio2.jpg",
    price: 680,
    flightTime: 9.5,
    sunshineHours: 7,
    exclusivity: "emerging",
    description:
      "Rio offers the perfect backdrop for your 'Latin American market research' that somehow always takes place near Ipanema Beach. The city's growing startup scene provides legitimacy for your presence, while the vibrant culture ensures your 'research' is never boring.",
    bestTimeToVisit: "December to March",
    currency: "Brazilian Real (R$)",
    forecast: [
      { day: "Today", temp: 28, sunny: true, condition: "Sunny" },
      { day: "Tomorrow", temp: 29, sunny: true, condition: "Sunny" },
      { day: "Day 3", temp: 27, sunny: false, condition: "Partly Cloudy" },
    ],
    founderHistory: [
      'Tech entrepreneur "exploring LATAM opportunities"',
      'VC partner "building relationships with Brazilian startups"',
      'Series A founder "researching expansion to South America"',
    ],
    workspaces: [
      { name: "Nex Coworking", type: "Co-working Space", wifiRating: 4 },
      { name: "Fasano Rio", type: "Luxury Hotel Workspace", wifiRating: 5 },
      { name: "Sofitel Ipanema", type: "Beach View Office", wifiRating: 4 },
    ],
    alibis: [
      "I'm meeting with potential partners for our Latin American expansion.",
      "We're considering opening a development office in Brazil to tap into local talent.",
      "I'm conducting market research for our product localization strategy.",
    ],
  },
  {
    id: 16,
    name: "Marrakech",
    country: "Morocco",
    region: "Africa",
    imageUrl: "/images/marrakech1.jpg",
    escapeImageUrl: "/images/marrakech2.jpeg",
    price: 450,
    flightTime: 3.5,
    sunshineHours: 9,
    exclusivity: "undiscovered",
    description:
      "Marrakech offers an exotic backdrop for your 'strategic thinking sessions' that happen to take place in luxurious riads. The city's unique aesthetic provides excellent content for your 'working remotely' social media posts that make your team both envious and suspicious.",
    bestTimeToVisit: "March to May, September to November",
    currency: "Moroccan Dirham (MAD)",
    forecast: [
      { day: "Today", temp: 28, sunny: true, condition: "Sunny" },
      { day: "Tomorrow", temp: 29, sunny: true, condition: "Sunny" },
      { day: "Day 3", temp: 30, sunny: true, condition: "Sunny" },
    ],
    founderHistory: [
      'Creative agency founder "seeking design inspiration"',
      'Tech CEO "exploring African market opportunities"',
      'VC partner "connecting with North African startups"',
    ],
    workspaces: [
      { name: "The Spot", type: "Co-working Space", wifiRating: 4 },
      { name: "La Mamounia", type: "Luxury Hotel Workspace", wifiRating: 5 },
      { name: "Royal Mansour", type: "Private Riad Office", wifiRating: 5 },
    ],
    alibis: [
      "I'm researching emerging markets in North Africa for potential expansion.",
      "Our design team needed authentic inspiration for our new product line.",
      "I'm meeting with potential partners to discuss our global strategy.",
    ],
  },
  {
    id: 17,
    name: "Sydney",
    country: "Australia",
    region: "Oceania",
    imageUrl: "/images/sydney.png",
    escapeImageUrl: "/images/sydney2.png",
    price: 950,
    flightTime: 14,
    sunshineHours: 7,
    exclusivity: "emerging",
    description:
      "Sydney's reputation as a business hub provides the perfect cover for your sunshine escape. The significant time difference from the US and Europe means you can claim to be 'working around the clock' while actually enjoying Bondi Beach during your daylight hours.",
    bestTimeToVisit: "November to March",
    currency: "Australian Dollar (A$)",
    forecast: [
      { day: "Today", temp: 24, sunny: true, condition: "Sunny" },
      { day: "Tomorrow", temp: 25, sunny: true, condition: "Sunny" },
      { day: "Day 3", temp: 23, sunny: false, condition: "Partly Cloudy" },
    ],
    founderHistory: [
      'Tech CEO "exploring APAC headquarters location"',
      'Series B founder "meeting with Australian investors"',
      'Product executive "researching APAC user preferences"',
    ],
    workspaces: [
      { name: "Fishburners", type: "Co-working Space", wifiRating: 5 },
      { name: "The Old Clare Hotel", type: "Boutique Workspace", wifiRating: 4 },
      { name: "Park Hyatt Sydney", type: "Luxury Office", wifiRating: 5 },
    ],
    alibis: [
      "I'm meeting with potential investors and partners in the APAC region.",
      "We're considering Sydney for our Asia-Pacific headquarters.",
      "I'm conducting user research with our Australian customer base.",
    ],
  },
  {
    id: 18,
    name: "Amalfi Coast",
    country: "Italy",
    region: "Europe",
    imageUrl: "/images/amalfi1.png",
    escapeImageUrl: "/images/amalfi2.png",
    price: 680,
    flightTime: 2.5,
    sunshineHours: 8,
    exclusivity: "undiscovered",
    description:
      "The Amalfi Coast offers sophisticated luxury for the discerning founder. Claim you're 'connecting with Italian design partners' while actually connecting with aperitivo and coastal views. The area's limited connectivity provides the perfect excuse for your delayed responses.",
    bestTimeToVisit: "May to September",
    currency: "Euro (€)",
    forecast: [
      { day: "Today", temp: 25, sunny: true, condition: "Sunny" },
      { day: "Tomorrow", temp: 26, sunny: true, condition: "Sunny" },
      { day: "Day 3", temp: 24, sunny: true, condition: "Sunny" },
    ],
    founderHistory: [
      'Luxury brand CEO "researching Italian craftsmanship"',
      'Design-focused founder "seeking aesthetic inspiration"',
      'Tech executive "hosting exclusive leadership retreat"',
    ],
    workspaces: [
      { name: "Villa Cimbrone", type: "Garden Workspace", wifiRating: 3 },
      { name: "Hotel Santa Caterina", type: "Seaside Office", wifiRating: 4 },
      { name: "Le Sirenuse", type: "Luxury Workspace", wifiRating: 4 },
    ],
    alibis: [
      "I'm meeting with potential European luxury partners for our premium product line.",
      "Our design team needed authentic Mediterranean inspiration.",
      "I'm hosting a strategic retreat for our executive leadership team.",
    ],
  },
  {
    id: 19,
    name: "Seychelles",
    country: "Seychelles",
    region: "Africa",
    imageUrl: "/placeholder.svg?height=600&width=800&text=Seychelles",
    escapeImageUrl: "/placeholder.svg?height=600&width=800&text=Seychelles+Beach",
    price: 1100,
    flightTime: 9,
    sunshineHours: 8,
    exclusivity: "undiscovered",
    description:
      "The Seychelles offers ultimate seclusion for the founder who needs to 'completely disconnect to solve complex strategic challenges.' The islands' remote location and exclusivity ensure you won't run into anyone who might question why your 'deep work' requires a snorkel.",
    bestTimeToVisit: "April to May, October to November",
    currency: "Seychellois Rupee (SCR)",
    forecast: [
      { day: "Today", temp: 29, sunny: true, condition: "Sunny" },
      { day: "Tomorrow", temp: 28, sunny: true, condition: "Sunny" },
      { day: "Day 3", temp: 29, sunny: false, condition: "Scattered Showers" },
    ],
    founderHistory: [
      'Post-exit founder "contemplating next venture"',
      'Tech CEO "conducting deep strategic planning"',
      'VC partner "recharging between fund cycles"',
    ],
    workspaces: [
      { name: "Four Seasons", type: "Private Villa Office", wifiRating: 4 },
      { name: "North Island Lodge", type: "Exclusive Workspace", wifiRating: 3 },
      { name: "Six Senses Zil Pasyon", type: "Ocean View Office", wifiRating: 4 },
    ],
    alibis: [
      "I needed complete isolation to solve some complex strategic challenges.",
      "I'm taking a brief executive retreat to map our five-year vision.",
      "I'm conducting research on sustainable tourism for our ESG initiatives.",
    ],
  },
  {
    id: 20,
    name: "Bora Bora",
    country: "French Polynesia",
    region: "Oceania",
    imageUrl: "/placeholder.svg?height=600&width=800&text=Bora+Bora",
    escapeImageUrl: "/placeholder.svg?height=600&width=800&text=Bora+Bora+Beach",
    price: 1500,
    flightTime: 12,
    sunshineHours: 7,
    exclusivity: "undiscovered",
    description:
      "Bora Bora represents the pinnacle of founder escapism. The island's overwater bungalows provide the perfect setting for 'deep strategic work' that mysteriously requires a lot of snorkeling. The remote location ensures no one will accidentally discover your 'executive retreat.'",
    bestTimeToVisit: "May to October",
    currency: "CFP Franc (XPF)",
    forecast: [
      { day: "Today", temp: 28, sunny: true, condition: "Sunny" },
      { day: "Tomorrow", temp: 29, sunny: true, condition: "Sunny" },
      { day: "Day 3", temp: 28, sunny: false, condition: "Scattered Showers" },
    ],
    founderHistory: [
      'Unicorn CEO "recharging after major funding round"',
      'Tech executive "developing long-term company vision"',
      'Serial entrepreneur "incubating new venture concepts"',
    ],
    workspaces: [
      { name: "Four Seasons", type: "Overwater Office", wifiRating: 4 },
      { name: "St. Regis", type: "Private Villa Workspace", wifiRating: 4 },
      { name: "Conrad Bora Bora", type: "Beachfront Office", wifiRating: 3 },
    ],
    alibis: [
      "I'm taking a strategic thinking retreat to map our next five years.",
      "I needed complete isolation to solve some complex product challenges.",
      "I'm conducting research on remote work effectiveness in different environments.",
    ],
  },
]
